# Change these first
owner: smacota 
repo: status-page 

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Удаляем cname, так как у вас нет своего домена
  # Раскомментируем baseUrl и указываем путь к вашему репозиторию
  baseUrl: /status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page."
  introMessage: This is my status page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/smacota/status-page
